### ISSUE TITLE
Reproduce results on 1% label data on coco dataset

### ISSUE THREAD

**Issue by tahirashehzadi** [JCZ404/Semi-DETR#1]
Hi,
   Thank you so much for your amazing work. I reproduce results on 1% label data on coco dataset. However i am getting 28.5 mAP on 1% label while your result on paper shows 30.50 mAP on 1% label. Can you elaborate this.
my config file: configs/detr_ssod/detr_ssod_dino_detr_r50_coco_120k.py

Thanks in advance!

**Comment by JCZ404** [comment]
Oops! It looks like this was due to my oversight. I'm really sorry about that! Unfortunately, I forgot to make the necessary correction in the configuration file. After reviewing the paper's settings, we should have used a batch size of 5 x 8, and the ratio of labeled images to unlabeled images on each GPU should have been 1:4. We will promptly update the configuration file to fix this issue. Your attention to detail is much appreciated, and we're grateful for bringing this to our notice.

Thanks!
