### ISSUE TITLE
the speed of the compiling is very slow

### ISSUE THREAD

**Issue by SISTMrL** [JCZ404/Semi-DETR#5]
<img width="345" alt="1693312379364" src="https://github.com/JCZ404/Semi-DETR/assets/47938053/64068252-db70-4cd6-b734-b5173bbe9067">

hello, when i run the code to build , the speed is very slow. 2 or 3 hours cannot compile the msdformattn, i have install the environment above as your readme shows. should i need to install the ninja to speed up the compiling? the compiling figure is shown as follows:
<img width="991" alt="1693312856572" src="https://github.com/JCZ404/Semi-DETR/assets/47938053/952532d2-3091-4827-89e7-3483ccd175dc">

**Comment by JCZ404** [comment]
Hi,  In my machine, it takes about ten minutes(maybe less) to finish the compile, while the process of unit test may consume considerable time. And generally, you can skip the unit test procedure. It's unclear why the compile is so slow in your machine, it's probably caused by your hardware condition. Trying to utilize the ninja to accelerate the compile process maybe is a good attempt.  Unfortunately, i can not provide you offline compiling version, since the deform-attn is a compiled  extension which needs to be compiled according to your hardware condition(e.g. cuda). The url in the setup has no much relationship about your compile process, and my machine has no access to the network. If your problem remain unsolved, maybe you can find some possible helpful clues in the original repo of deformable-detr.

**Comment by SISTMrL** [comment]
the cuda version i used is 11.3, is it the reason for slow compiling speed?
